cineboard/urls.py
from django.urls import path
from .import views

app_name='cineboard'

urlpatterns = [
    path('register_cine/', views.RegisterView.as_view(), name='register_cine'),
    path('login_cine/', views.AuthLoginView.as_view(), name='login_cine'),
    path('logout_cine/', views.AuthLogoutView.as_view(), name='logout_cine'),
    path('all_films/', views.AllFilmsListView.as_view(), name='all_films'),
    path('all_films/<int:id>/update/', views.UpdateFilmView.as_view(), name='update'),
    path('all_films/<int:id>/delete/', views.DeleteFilmView.as_view(), name='delete'),
    path('create_film/', views.CreateFilmView.as_view(), name='create_film')
]

main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import FirstPageView, TextPageView, BlogListView, BlogDetailView, SearchView
from tags.views import all_products, drinks_products, meal_products

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_page/', FirstPageView.as_view(), name='first_page'),
    path('text_page/', TextPageView.as_view(), name='text_page'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog_list/<int:id>/', BlogDetailView.as_view(), name='blog_detail'),
    path('', include('todo.urls')),
    path('', include('users.urls')),
    path('captcha/', include('captcha.urls')),
    path('search/', SearchView.as_view(), name='search'),
    path('all_products/', all_products, name='all_products'),
    path('drinks_products/', drinks_products, name='drinks_products'),
    path('meal_products/', meal_products, name='meal_products'),
    path('', include('cineboard.urls')),

    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('todo_list/', views.ReadTodoView.as_view(), name='todo_list'),
  path('create_todo/', views.CreateTodo.as_view(), name="create_todo"),
  path('update_todo/<int:id>/', views.UpdateTodoView.as_view(), name='update_todo'),
  path('delete_todo/<int:id>/', views.DeleteTodoView.as_view(), name='delete_todo'),
]

cineboard/models.py
from django.db import models

class Tag(models.Model):
    name = models.CharField(max_length=100, default='Романтика')



class Films(models.Model):
    GENRE = (
        ('Фантастика', 'Фантастика'),
        ('Хорор', 'Хоррор')
    )
    title = models.CharField(max_length=100, default='фильм1')
    description = models.TextField(default='Описание фильма')
    genre = models.CharField(max_length=100, choices=GENRE, default='Фантастика')
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)

class Rating(models.Model):
    MARKS = (
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ('4', "4"),
        ('5', '5')
    )
    choice_films = models.ForeignKey(Films, on_delete=models.CASCADE, related_name='rating')
    marks = models.CharField(max_length=100, choices=MARKS, default='3', null=True)

cineboard/forms.py
from django import forms
from . import models



class FilmsForm(forms.ModelForm):
    class Meta:
        model = models.Films
        fields = '__all__'

cineboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from . import models, forms
from django.http import HttpResponse


#пункт 2 
class CreateFilmView(generic.CreateView):
    model = models.Films
    form_class = forms.FilmsForm
    template_name = 'cineboard/createFilm.html'
    success_url = '/all_films/'


#Update
class UpdateFilmView(generic.UpdateView):
  model = models.Films
  form_class = forms.FilmsForm
  template_name = 'cineboard/updateFilm.html'
  success_url = '/all_films/'

  def get_object(self, *args, **kwargs):
    film_id = self.kwargs.get('id')
    return get_object_or_404(models.Films, id=film_id)
  
  def form_valid(self, form):
    print(form.cleaned_data)
    return super(UpdateFilmView, self).form_valid(form=form)


#Delete
class DeleteFilmView(generic.DeleteView):
  template_name = 'cineboard/confirm_delete_film.html'
  success_url = '/all_films/'

  def get_object(self, *args, **kwargs):
    film_id = self.kwargs.get('id')
    return get_object_or_404(models.Films, id=film_id)









#пункт 1 с регистрацией
class RegisterView(generic.View):
    def get(self, request):
        form = UserCreationForm()
        return render(request, template_name='cineboard/register_cine.html', context={'form':form})
    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login_cine/')
        return render(request, template_name='cineboard/register_cine.html', context={'form': form})
    

class AuthLoginView(generic.View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, 'cineboard/login_cine.html', {'form':form})
    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('cineboard:all_films')
        return render(request, 'cineboard/login_cine.html', {'form':form})


class AllFilmsListView(LoginRequiredMixin, generic.ListView):
    model = models.Films
    template_name = 'cineboard/tv_list.html'
    context_object_name = 'tv_lst'


class AuthLogoutView(generic.View):
    def get(self, request):
        logout(request)
        return redirect('cineboard:login_cine')

templates/cineboard/confirm_delete_film.html
<form method="POST">
    {% csrf_token %}
    <h1>Вы действительно хотите удалить этот фильм?</h1>
    <button type="submit">Да</button>
</form>

templates/cineboard/createFilm.html
<h1>Добавить фильм</h1>

<form action="{% url 'cineboard:create_film' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Отправить</button>
</form>

templates/cineboard/login_cine.html
<h1>Авторизация Кино</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Авторизация</button>
</form> 

templates/cineboard/register_cine.html
<h1>Регистрация Кино</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Регистрация</button>
</form> 

templates/cineboard/tv_list.html
<h1>Супер, продолжай дальше</h1>

<h1>Фильмы</h1>
<a href="{% url 'cineboard:create_film' %}">Добавить фильм</a>

<ol>
  {% for i in tv_lst %}
  <li>
    <h2>{{ i.title }}</h2>
    <p>{{ i.created_at }}</p>
    <p>{{ i.description }}</p>

    Теги:
    {% for tag in i.tags.all %}
      {{ tag.name }}{% if not forloop.last %}, {% endif %}
    {% empty %}
      без тегов
    {% endfor %}

    <br>

    <h3>Комменты</h3>
    <ol>
      {% for comment in i.rating.all %}
      <li>
        <strong>{{ comment.stars }}★</strong><br>
        <p>{{ comment.text }}</p>
      </li>
      {% empty %}
      <li>Комментариев пока нет</li>
      {% endfor %}
    </ol>

   <a href="{% url 'cineboard:update' i.id %}">Изменить фильм</a>
<a href="{% url 'cineboard:delete' i.id %}">Удалить фильм</a>

  </li>
  {% endfor %}
</ol>

templates/cineboard/updateFilm.html
<h1>Изменить фильм</h1>

<form  method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Изменить</button>
</form>