cineboard/urls.py
from django.urls import path
from .import views

app_name='cineboard'

urlpatterns = [
    path('register_cine/', views.RegisterView.as_view(), name='register_cine'),
    path('login_cine/', views.AuthLoginView.as_view(), name='login_cine'),
    path('logout_cine/', views.AuthLogoutView.as_view(), name='logout_cine'),
    path('all_films/', views.AllFilmsListView.as_view(), name='all_films'),
    path('all_films/<int:id>/update/', views.UpdateFilmView.as_view(), name='update'),
    path('all_films/<int:id>/delete/', views.DeleteFilmView.as_view(), name='delete'),
    path('create_film/', views.CreateFilmView.as_view(), name='create_film')
]

main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog.views import FirstPageView, TextPageView, BlogListView, BlogDetailView, SearchView
from tags.views import all_products, drinks_products, meal_products

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_page/', FirstPageView.as_view(), name='first_page'),
    path('text_page/', TextPageView.as_view(), name='text_page'),
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog_list/<int:id>/', BlogDetailView.as_view(), name='blog_detail'),
    path('', include('todo.urls')),
    path('', include('users.urls')),
    path('captcha/', include('captcha.urls')),
    path('search/', SearchView.as_view(), name='search'),
    path('all_products/', all_products, name='all_products'),
    path('drinks_products/', drinks_products, name='drinks_products'),
    path('meal_products/', meal_products, name='meal_products'),
    path('', include('cineboard.urls')),

    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('todo_list/', views.ReadTodoView.as_view(), name='todo_list'),
  path('create_todo/', views.CreateTodo.as_view(), name="create_todo"),
  path('update_todo/<int:id>/', views.UpdateTodoView.as_view(), name='update_todo'),
  path('delete_todo/<int:id>/', views.DeleteTodoView.as_view(), name='delete_todo'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('logout/', views.AuthLogoutView.as_view(), name='logout'),
    path('user_list/', views.UserListView.as_view(), name='user_list'),
]

blog/models.py
from django.db import models

class Blog(models.Model):
  CATEGORY_BLOG = (
    ('Машины', 'Машины'),
    ('Недвижимость', 'Недвижимость'),
    ('Кино', 'Кино')
  )
  title = models.CharField(max_length=50, verbose_name='укажите название блога')
  images = models.ImageField(upload_to='blog/', verbose_name='загрузите фото')
  description = models.TextField(verbose_name='укажите описание блога')
  link_blog = models.URLField(verbose_name='вставьте доп ссылку на контент')
  category_blog = models.CharField(max_length=100, choices=CATEGORY_BLOG, default='Кино')
  video_url = models.URLField(verbose_name='укажите ссылку с youTube', null=True, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.title
  
  class Meta:
    verbose_name = 'новость'
    verbose_name_plural = 'новости'


class Reviews(models.Model):
  STARS = (
    ('⭐', '⭐'),
    ('⭐⭐', '⭐⭐'),
    ('⭐⭐⭐', '⭐⭐⭐'),
    ('⭐⭐⭐⭐', '⭐⭐⭐⭐'),
    ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'),
  )
  choice_blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='post', verbose_name='выберите пост для коммента')
  text = models.TextField(verbose_name='оставьте отзыв')
  stars = models.CharField(max_length=100, choices=STARS, verbose_name='поставьте оценку об блоге', default='⭐⭐⭐⭐')
  
  def __str__(self):
    return f'{self.choice_blog} - {self.stars}'
  
  class Meta:
    verbose_name = 'коммент'
    verbose_name_plural = 'комменты'







#  many to many, one to many, one to one

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from blog.models import Blog
from django.core.paginator import Paginator
from django.views import generic




#Search

class SearchView(generic.ListView):
  def get(self, request):
    query = request.GET.get('s', '')
    if query:
       blog_lst = Blog.objects.filter(title__icontains=query)
    else:
      blog_lst = Blog.objects.none
    context = {
    'blog_lst': blog_lst,
    's': query,
     }
    return render(request, template_name='blog.html', context=context)



# def search_view(request):
#   query = request.GET.get('s', '')
#   blog_lst = Blog.objects.filter(title__icontains=query) if query else Blog.objects.none
#   context = {
#     'blog_lst': blog_lst,
#     's': query,
#   }
#   return render(request, template_name='blog.html', context=context)





class BlogDetailView(generic.DetailView):
  template_name = 'blog_detail.html'
  context_object_name = 'blog_id'

  def get_object(self, *args, **kwargs):
    blog_id = self.kwargs.get('id')
    return get_object_or_404(Blog, id=blog_id)


class BlogListView(generic.ListView):
    model = Blog
    template_name = 'blog.html'
    context_object_name = 'blog_lst'
    ordering = ['-id']

    def get_queryset(self):
      return Blog.objects.all()


class FirstPageView(generic.View):
  def get(self, request):
    return HttpResponse('Привет это мой первый проект на Django!')

class TextPageView(generic.View):
  def get(self, request):
    return HttpResponse('Lorem Ipsum is simply ' \
    'dummy text of the printing and typesetting ' \
    'industry. Lorem Ipsum has been the industrys' \
    ' standard dummy text ever since the 1500s,' \
    ' when an unknown printer took a galley of ' \
    'type and scrambled it to make a type specimen book.' \
    ' It has survived not only five centuries, ' \
    'but also the leap into electronic typesetting, ' \
    'remaining essentially unchanged. It was popularised '
    'in the 1960s with the release of Letraset sheets ' \
    'containing Lorem Ipsum passages, and more recently' \
    ' with desktop publishing software like Aldus' \
    ' PageMaker including versions of Lorem Ipsum')

templates/blog.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>


<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    
     <a class="navbar-brand" href="#">
      <img src="{% static 'логотип/blog.jpg' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
      GEEKS 56-1
    </a>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'users:register' %}">Регистрация</a>
          <a class="nav-link active" aria-current="page" href="{% url 'cineboard:register_cine' %}">Регистрация Фильмы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo_list' %}">TODO</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'all_products' %}">Tags</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>




<!-- Search -->
 <form action="{% url 'search' %}" method="GET">
    <input type="text" type="search" name="s" placeholder="Напишите название новости чтобы найти">
    <button type="submit">Поиск</button>
 </form> 
<h1>Новостной блог</h1>
<ol>
  {% for i in blog_lst %}

  <li>
    <h2>{{ i.title }}</h2>
    <img src="{{ i.images.url }}" alt="" width="400" height="350">
    <p>{{ i.created_at }}</p>
    <a href="/blog_list/{{ i.id }}/">Подробнее</a>
  </li>

  {% endfor %}
</ol>

<!-- Пагинация -->
<div style="display: flex; justify-content: center; margin: 20px 0;">
  <div>
    {% if blog_lst.has_previous %}
      <a href="?page=1">« Первая</a>
      <a href="?page={{ blog_lst.previous_page_number }}">‹ Предыдущая</a>
    {% endif %}

    <span>Страница {{ blog_lst.number }} из {{ blog_lst.paginator.num_pages }}</span>

    {% if blog_lst.has_next %}
      <a href="?page={{ blog_lst.next_page_number }}">Следующая ›</a>
      <a href="?page={{ blog_lst.paginator.num_pages }}">Последняя »</a>
    {% endif %}
  </div>
</div>

templates/blog_detail.html
    <h2>{{ blog_id.title }}</h2>
    <img src="{{ blog_id.images.url }}" alt="" width="400" height="350">
    <p>{{ blog_id.description }}</p>
    <a href="{{ blog_id.link_blog}}" target="_blank">перейти на страницу</a>
    <p>{{ blog_id.category_blog }}</p>
    <iframe src="{{ blog_id.video_url }}" frameborder="0"></iframe>
    <p>{{ blog_id.created_at }}</p>

    <h2>Комменты</h2>
    <ol>
  {% for i in blog_id.post.all %}

  <li>
    <h3>{{ i.stars }}</h3>
    <p>{{ i.text }}</p>
  </li>

  {% endfor %}
</ol>

templates/confirm_delete.html
<form method="POST">
    {% csrf_token %}
    <h1>Вы действительно хотите удалить эту задачу?</h1>
    <button type="submit">Да</button>
</form>
<a href="{% url 'todo_list' %}">Назад</a>

templates/create_todo.html
<h1>Добавить Задачу</h1>

<form action="{% url 'create_todo' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Отправить</button>
</form>

templates/todo_list.html
<h1>TODO</h1>
<ol>
  <a href="{% url 'create_todo' %}">Добавить Задачу</a>
  {% for i in todo %}
  <li>
    <h2>{{ i.title }}</h2>
    <p>{{ i.created_at }}</p>
    <p>{{ i.choice_type }}</p>
    <a href="/delete_todo/{{i.id}}/">Удалить Задачу</a>
    <a href="/update_todo/{{i.id}}/">Изменить Задачу</a>
  </li>
  {% endfor %}
</ol>

templates/update_todo.html
<h1>Изменить Задачу</h1>

<form  method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Изменить</button>
</form>